
services:
  mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: lastDB
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  spring-app:
    image: ${DOCKERHUB_REPO}/backend:${BUILD_NUMBER}
    ports:
      - "8085:8085"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/lastDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
      ACTIVATION_URL: http://localhost:8085/api/v1/auth/activate-account
      TOKEN_EXPIRATION_MINUTES: 360
    volumes:
      - uploads:/app/uploads/justificatifs
    networks:
      - app-network

  frontend:
    image: ${DOCKERHUB_REPO}/frontend:${BUILD_NUMBER}
    ports:
      - "3000:80"
    depends_on:
      spring-app:
        condition: service_started
    networks:
      - app-network

  # Exporter pour MySQL
  mysqld_exporter:
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: "exporter:exporterpassword@tcp(mysql-db:3306)/"
    depends_on:
      - mysql-db
    networks:
      - app-network


  # Exporter pour les métriques système
  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - app-network

  # Exporter pour les métriques des conteneurs Docker
  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8081:8080"  # Changement de 8080:8080 à 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker/
    networks:
      - app-network

  # Prometheus
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/'
      - '--storage.tsdb.retention.time=30d'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
    depends_on:
      - mysqld_exporter
      - node_exporter
      - cadvisor
      - alertmanager
    networks:
      - app-network

  # Alertmanager
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    environment:
      SMTP_SMARTHOST: ${SMTP_SMARTHOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_AUTH_USERNAME: ${SMTP_AUTH_USERNAME}
      SMTP_AUTH_PASSWORD: ${SMTP_AUTH_PASSWORD}
    networks:
      - app-network

  # Grafana
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  uploads:
  grafana_data:
