groups:
  - name: example
    rules:
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{image!="",container!="POD"}[2m]) > 0.7
        for: 2m
        labels:
          severity: "critical"
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 70% for more than 2 minutes."
